#!/usr/bin/env node
/**
 * resolve-conflicts.js
 *
 * This script reads the 'conflicting.css' file (generated by your merge script) and resolves conflicts
 * by merging rules that share the same selector and context (e.g. rules inside the same @media block).
 * The merging follows CSS cascade principles—later declarations override earlier ones—and if a property
 * is deemed to be a color, its value is converted to hex so that equivalent color values are normalized.
 *
 * The final merged output is written to 'conflicting-resolve.css'.
 *
 * Usage: node resolve-conflicts.js
 */

import fs from 'fs';
import path from 'path';
import postcss from 'postcss';
import Color from 'color'; // npm install color

// Path to the conflicting CSS file.
const conflictingCssPath = path.join(process.cwd(), 'conflicting.css');
if (!fs.existsSync(conflictingCssPath)) {
  console.error("Error: 'conflicting.css' not found.");
  process.exit(1);
}
const cssContent = fs.readFileSync(conflictingCssPath, 'utf8');

// Parse the CSS with PostCSS.
const root = postcss.parse(cssContent, { from: conflictingCssPath });

/**
 * We'll gather each rule along with its "context".
 * The context is defined as any wrapping at-rule (e.g. "@media (max-width:600px)") that encloses the rule.
 * Each rule object will have:
 *   - selector: the CSS selector (assumed to be a simple class selector)
 *   - context: an array of strings representing wrapping at-rules (outermost first)
 *   - declarations: an array of { prop, value } objects
 *   - order: a number representing the order in which the rule was encountered (to simulate cascade)
 */
let rulesList = [];
let ruleOrder = 0;

/**
 * Recursively traverse the AST to collect rules along with their context.
 * @param {Object} node - A PostCSS node.
 * @param {Array} context - An array of context strings (e.g. at-rules).
 */
function gatherRules(node, context) {
  if (node.type === 'rule') {
    ruleOrder++;
    // A rule might contain multiple selectors (comma separated)
    const selectors = node.selector.split(',').map(s => s.trim());
    selectors.forEach(selector => {
      // Extract declarations for this rule.
      const declarations = [];
      node.walkDecls(decl => {
        declarations.push({
          prop: decl.prop.trim(),
          value: decl.value.trim()
        });
      });
      rulesList.push({
        selector,
        context: [...context],
        declarations,
        order: ruleOrder
      });
    });
  } else if (node.type === 'atrule') {
    // Construct a string representation of the at-rule.
    const atRuleStr = `@${node.name} ${node.params}`.trim();
    if (node.nodes && node.nodes.length > 0) {
      node.nodes.forEach(child => {
        gatherRules(child, [...context, atRuleStr]);
      });
    }
  } else if (node.nodes) {
    node.nodes.forEach(child => {
      gatherRules(child, context);
    });
  }
}

// Start gathering rules from the root with an empty context.
gatherRules(root, []);

/**
 * Group rules by a composite key (selector + context).
 * We use JSON.stringify({selector, context}) as the key.
 */
const groups = {};
rulesList.forEach(rule => {
  const key = JSON.stringify({ selector: rule.selector, context: rule.context });
  if (!groups[key]) {
    groups[key] = [];
  }
  groups[key].push(rule);
});

/**
 * Define a set of properties that are likely to be colors.
 * (This is a heuristic; you can add more properties as needed.)
 */
const colorProperties = new Set([
  'color',
  'background',
  'background-color',
  'border',
  'border-color',
  'outline-color',
  'text-decoration-color'
]);

/**
 * Attempt to convert a color value to hex.
 * If the conversion succeeds, return the hex code (in uppercase).
 * If the value contains "!important", preserve it.
 * If conversion fails (i.e. not a valid color), return the original value.
 *
 * @param {string} value - The CSS color value.
 * @returns {string} The hex representation (or original value if conversion fails).
 */
function convertToHex(value) {
  try {
    // Check for !important and remove it temporarily.
    const important = value.includes('!important') ? ' !important' : '';
    const cleanValue = value.replace('!important', '').trim();
    const hex = Color(cleanValue).hex().toUpperCase();
    return hex + important;
  } catch (e) {
    return value;
  }
}

/**
 * For each group of rules (same selector and context), merge their declarations
 * following cascade rules (later declarations override earlier ones).
 * For color properties, convert values to hex.
 */
const resolvedRules = [];
for (const groupKey in groups) {
  const rules = groups[groupKey];
  // Sort rules in the order they appeared (ascending).
  rules.sort((a, b) => a.order - b.order);
  // Merge declarations: later declarations override earlier ones.
  // We'll also record the order in which each property first appears for output ordering.
  const mergedDeclarations = {};
  const propertyOrder = {};
  rules.forEach(rule => {
    rule.declarations.forEach(decl => {
      const prop = decl.prop;
      let value = decl.value;
      if (colorProperties.has(prop)) {
        value = convertToHex(value);
      }
      mergedDeclarations[prop] = value;
      // Only record the first appearance order.
      if (!(prop in propertyOrder)) {
        propertyOrder[prop] = rule.order;
      }
    });
  });
  // Convert merged declarations into an array sorted by the order of first appearance.
  const mergedDeclsArray = Object.keys(mergedDeclarations)
    .sort((a, b) => propertyOrder[a] - propertyOrder[b])
    .map(prop => ({ prop, value: mergedDeclarations[prop] }));
  const { selector, context } = JSON.parse(groupKey);
  resolvedRules.push({
    selector,
    context,
    declarations: mergedDeclsArray
  });
}

/**
 * Helper: Wrap a CSS rule with its context (i.e. at-rules).
 * The innermost rule is wrapped by its immediate context, and so on.
 * @param {Array} contextArr - Array of context strings.
 * @param {string} ruleContent - The CSS rule content.
 * @returns {string} The wrapped rule.
 */
function wrapRule(contextArr, ruleContent) {
  let output = ruleContent;
  for (let i = contextArr.length - 1; i >= 0; i--) {
    output = `${contextArr[i]} {\n${indent(output, 1)}\n}\n`;
  }
  return output;
}

/**
 * Helper: Generate a CSS rule string given a selector and its declarations.
 * @param {string} selector - The CSS selector.
 * @param {Array} declarations - Array of { prop, value } objects.
 * @returns {string} The CSS rule as a string.
 */
function generateRule(selector, declarations) {
  let ruleStr = `${selector} {\n`;
  declarations.forEach(decl => {
    ruleStr += `    ${decl.prop}: ${decl.value};\n`;
  });
  ruleStr += `}\n`;
  return ruleStr;
}

/**
 * Helper: Indent a block of text by a given level.
 * @param {string} text - The text to indent.
 * @param {number} level - The number of indentations.
 * @returns {string} The indented text.
 */
function indent(text, level) {
  const indentStr = '    '.repeat(level);
  return text.split('\n').map(line => (line ? indentStr + line : line)).join('\n');
}

// Generate the final resolved CSS string.
let resolvedCss = '';
resolvedRules.forEach(rule => {
  let ruleContent = generateRule(rule.selector, rule.declarations);
  ruleContent = wrapRule(rule.context, ruleContent);
  resolvedCss += ruleContent + "\n";
});

// Write the output to 'conflicting-resolve.css'.
const resolvedPath = path.join(process.cwd(), 'conflicting-resolve.css');
fs.writeFileSync(resolvedPath, resolvedCss, 'utf8');

console.log(`Processed 'conflicting.css' and generated '${resolvedPath}'.`);